import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Session,flags,words} from '../src/terminal/session.js';import {Client} from '../src/terminal/client.js';
const fixture=async()=>{const root=await mkdtemp(join(tmpdir(),'seudaily-ink-test-'));const session=new Session({command:'chat',skill:[]},root);const requests:any[]=[];session.client.json=async(path,method='GET',body)=>{requests.push({path,method,body});if(path==='/app/skills')return {skills:[{name:'training-plan-audit'}]};if(path.includes('/run?'))return {pending:null};if(path==='/app/settings')return {fields:[{name:'SECRET',value:'do-not-display'},{name:'SEUDAILY_FULL_ACCESS',value:'false'}]};return {status:'completed',data:{courses:[],plans:[],customizations:{semester:{}}}};};await session.initialize();return {root,session,requests,close:()=>rm(root,{recursive:true,force:true})};};
test('commands quote paths and reject unknown/missing options',()=>{assert.deepEqual(words('attach "C:\\Docs\\a b.pdf"'),['attach','C:\\Docs\\a b.pdf']);assert.throws(()=>words('"broken'));assert.throws(()=>flags(['--bad'],{}));assert.throws(()=>flags(['--semester'],{'--semester':true}));});
test('cached schedule, programs validation, skill context, persistent input history',async()=>{const f=await fixture();try{await f.session.submit('/schedule --date 2026-10-02');assert.match(f.requests.at(-1).path,/localOnly=true/);assert.match(f.requests.at(-1).path,/date=2026-10-02/);assert.equal(f.session.page,'schedule');await assert.rejects(f.session.submit('/programs --page 0'));await f.session.submit('/skill training-plan-audit');let body:any;f.session.client.stream=async function*(b){body=b;yield {type:'text-delta',payload:{text:'答复'}};yield {type:'finish',payload:{}};};assert.equal(await f.session.submit('问题'),0);assert.deepEqual(body.requestContext.seudailySkills,['training-plan-audit']);assert.equal(f.session.messages.at(-1)?.text,'答复');assert.equal(f.session.inputHistory.at(-1),'问题');await f.session.submit('第二个问题');assert.deepEqual(body.requestContext.seudailySkills,[]);const second=new Session({command:'chat'},f.root);second.client=f.session.client;await second.initialize();assert.equal(second.inputHistory.at(-1),'第二个问题');}finally{await f.close();}});
test('approval consumes bound token, rejects repeated approval, restores server state on failure',async()=>{const f=await fixture();try{let body:any;f.session.client.stream=async function*(b){body=b;yield {type:'tool-approval-request',payload:{approvalId:'approval',toolName:'write',args:{path:'x'}}};};assert.equal(await f.session.submit('写入'),3);const token=f.session.pending.runToken;f.session.client.stream=async function*(b){body=b;yield {type:'finish',payload:{}};};await f.session.submit('/reject');assert.equal(body.requestContext.seudailyRunToken,token);assert.equal(body.messages[0].content[0].approved,false);await assert.rejects(f.session.submit('/approve'),/没有待审批/);f.session.pending={approvalId:'next',runToken:'next-token'};f.session.client.stream=async function*(){throw new Error('network');};await assert.rejects(f.session.submit('/approve'));assert.equal(f.session.pending,null);}finally{await f.close();}});
test('writes require confirmation and secret settings never appear in messages',async()=>{const f=await fixture();try{await f.session.submit('/mode extra');assert.equal(f.requests.filter(r=>r.method==='POST').length,0);await f.session.submit('n');assert.equal(f.requests.filter(r=>r.method==='POST').length,0);await f.session.submit('/mode normal');await f.session.submit('y');assert.equal(f.requests.at(-1).method,'POST');await f.session.submit('/mode');assert.ok(!JSON.stringify(f.session.messages).includes('do-not-display'));f.session.actions.set('act',{text:'change'});await f.session.submit('/apply act');await f.session.submit('yes');assert.equal(f.session.actions.has('act'),false);await assert.rejects(f.session.submit('/apply act'));}finally{await f.close();}});
test('login accepts known resume and forwards structured resume ID',async()=>{const f=await fixture();try{await assert.rejects(f.session.submit('/login arbitrary'));f.session.auth.set('known',{id:'known'});const original=f.session.client.json.bind(f.session.client);f.session.client.json=async(path,...rest)=>path.includes('/auth-resumes/')?{status:'completed',resumeId:'trusted'}:original(path,...rest);let body:any;f.session.client.stream=async function*(b){body=b;yield {type:'finish',payload:{}};};await f.session.submit('/login known');assert.equal(body.requestContext.seudailyAuthResumeId,'trusted');assert.equal(f.session.auth.has('known'),false);}finally{await f.close();}});
test('cancel passes exact active run token and stops model iteration',async()=>{const f=await fixture();try{let started!:()=>void;const ready=new Promise<void>(r=>started=r);f.session.client.stream=async function*(b,signal){yield {type:'text-delta',payload:{text:'partial'}};started();await new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(new Error('aborted')),{once:true}));};const turn=f.session.submit('long');await ready;const token=f.session.runToken;await f.session.cancel();assert.equal(await turn,130);assert.equal(f.requests.at(-1).body.runToken,token);assert.equal(f.session.busy,false);}finally{await f.close();}});
test('document attachment sends multipart and has size/type limits',async()=>{const f=await fixture();try{await writeFile(join(f.root,'a.pdf'),'PDF');f.session.client.request=async(_path,init)=>{assert.ok(init?.body instanceof FormData);return new Response(JSON.stringify({contextRef:'doc'}));};await f.session.submit('/attach "a.pdf"');assert.equal(f.session.documents[0].contextRef,'doc');await f.session.submit('/detach');assert.equal(f.session.documents.length,0);}finally{await f.close();}});
test('SSE handles fragmented UTF8/CRLF/multiple data lines, detects dropped streams',async()=>{const original=globalThis.fetch;try{const content='data: {"type":"text-delta",\r\ndata: "payload":{"text":"中文"}}\r\n\r\ndata: {"type":"finish","payload":{}}\n\n';const bytes=new TextEncoder().encode(content);globalThis.fetch=async()=>new Response(new ReadableStream({start(c){for(let i=0;i<bytes.length;i++)c.enqueue(bytes.slice(i,i+1));c.close();}}));const client=new Client();const events=[];for await(const event of client.stream({},new AbortController().signal))events.push(event);assert.equal(events[0].payload.text,'中文');globalThis.fetch=async()=>new Response('data: {"type":"text-delta","payload":{"text":"partial"}}\n\n');await assert.rejects(async()=>{for await(const event of client.stream({},new AbortController().signal)){}},/提前结束/);}finally{globalThis.fetch=original;}});

import {commandSuggestions, attachmentSuggestions} from '../src/terminal/completion.js';
test('completion preserves flags, dynamic skills and quoted attachment paths',async()=>{
 assert.deepEqual(commandSuggestions('/ ',[]),[]);
 assert.deepEqual(commandSuggestions('/skill train',['training-plan-audit']),['/skill training-plan-audit']);
 assert.deepEqual(commandSuggestions('/课表 --s',[]),['/课表 --sync','/课表 --semester','/课表 --start-date','/课表 --semesters']);
 const root=await mkdtemp(join(tmpdir(),'ink-completion-'));
 try { await writeFile(join(root,'a file.pdf'),'test');assert.deepEqual(await attachmentSuggestions('/attach a',root),['/attach "a file.pdf"']);assert.deepEqual(await attachmentSuggestions('/attach "a f',root),['/attach "a file.pdf"']); } finally {await rm(root,{recursive:true,force:true});}
});
import {Composer} from '../src/terminal/composer.js';
import {programDocument,periodTimes} from '../src/terminal/course-layout.js';
import {telemetryLabel} from '../src/terminal/telemetry.js';
test('paste elements expand original data and delete atomically with surrounding edits',()=>{
 const draft=new Composer(), content=Array.from({length:20},(_,i)=>'原始行'+i).join('\n');
 draft.set('before ',7); draft.paste(content);draft.set(draft.text+' after',draft.text.length+6);
 assert.equal(draft.expanded(),'before '+content+' after');
 const end=draft.text.indexOf(']')+1;draft.set(draft.text,end);draft.set(draft.text.slice(0,end-1)+draft.text.slice(end),end-1);
 assert.equal(draft.text,'before  after');assert.equal(draft.expanded(),'before  after');
 draft.set('',0);draft.paste(content);const first=draft.text;draft.paste(content+'two');assert.equal(draft.expanded(),content+content+'two');
 draft.set(draft.text,0);draft.set(draft.text.slice(1),0);assert.match(draft.expanded(),/two$/);assert.equal(draft.expanded(),content+'two');
 draft.set('',0);draft.set(first,first.length);assert.equal(draft.expanded(),first,'literal placeholders must not expand');
 draft.set('',0);draft.paste(content);draft.set(draft.text,draft.cursor-1);assert.equal(draft.cursor,0,'cursor jumps over the element');
});
test('program layout uses web credit totals, requirements and per-semester statuses',()=>{
 const plan={title:'培养方案',requiredCredits:150,officialCompletedCredits:0,completedCredits:58,progress:38.7,creditSummary:{studying:28.75,remaining:92,generalElectiveCompleted:6},studyRequirements:[{name:'通识选修课',requiredCredits:10,note:'至少10学分'}]};
 const course={name:'程序设计',code:'A1',credits:3,nature:'必修',group:'专业',status:'studying',semesterOptions:[{value:'2025-1',label:'2025秋',status:'completed'},{value:'2026-1',label:'2026秋',status:'studying'}]};
 const doc=programDocument(plan,[course],126);assert.match(doc.rows.map(r=>r.text).join('\n'),/已完成 58/);assert.match(doc.rows.map(r=>r.text).join('\n'),/通识选修课/);assert.equal(doc.entries.length,2);assert.equal(doc.entries[0].status,'completed');assert.equal(programDocument(plan,[course],70,'2026-1').entries.length,1);assert.equal(periodTimes[1],'08:00–08:45');
});
test('usage reports actual cache hit rate and unknown metrics without invented values',()=>{
 const label=telemetryLabel('deepseek-test','默认',{prompt_tokens:1000,completion_tokens:200,total_tokens:1200,prompt_cache_hit_tokens:750});assert.match(label,/1,200/);assert.match(label,/75.0%/);assert.match(telemetryLabel('—','默认',{}),/缓存 —/);
});
test('restoring usage replaces a run snapshot without counting it twice',async()=>{const f=await fixture();try{f.session.recordUsage('run',{prompt_tokens:100,total_tokens:150});f.session.recordUsage('run',{prompt_tokens:100,total_tokens:150});f.session.recordUsage('second',{prompt_tokens:50,total_tokens:60});assert.equal(f.session.usage.total_tokens,210);f.session.recordUsage('run',{prompt_tokens:120,total_tokens:170});assert.equal(f.session.usage.total_tokens,230);}finally{await f.close();}});

test('reasoning is collected without verbose, restores independently from answer, and controls reset',async()=>{const f=await fixture();try{f.session.client.stream=async function*(){yield {type:'reasoning-start',payload:{}};yield {type:'reasoning-delta',payload:{text:'模型思考'}};yield {type:'reasoning-delta',payload:{text:'后续'}};yield {type:'reasoning-end',payload:{}};yield {type:'text-delta',payload:{text:'答案'}};yield {type:'finish',payload:{}};};await f.session.submit('问题');assert.equal(f.session.messages.at(-1)?.reasoning,'模型思考后续');assert.equal(f.session.messages.at(-1)?.text,'答案');await f.session.submit('/thinking');assert.equal(f.session.reasoningExpanded,true);await f.session.submit('/copy-on-select on');assert.equal(f.session.copyOnSelect,true);await f.session.submit('/copy-on-select off');assert.equal(f.session.copyOnSelect,false);await f.session.submit('新问题');assert.equal(f.session.reasoningExpanded,false);f.session.client.json=async()=>({messages:[{role:'assistant',content:{parts:[{type:'reasoning',text:'历史思考'},{type:'text',text:'历史回答'}]}}]});await f.session.history();assert.equal(f.session.messages.at(-1)?.reasoning,'历史思考');assert.equal(f.session.messages.at(-1)?.text,'历史回答');}finally{await f.close();}});

test('resume without ID lists first, cancellation leaves thread unchanged, explicit selection resumes exact ID',async()=>{const f=await fixture();try{const current=f.session.threadId;f.session.client.threads=async()=>[{id:'one',resourceId:'seudaily-web-local',title:'课程讨论',updatedAt:'2026-10-03'},{id:'two',resourceId:'seudaily-web-local',title:'中文测试',updatedAt:'2026-10-02'}];await f.session.submit('/resume');assert.equal(f.session.threadId,current);assert.equal(f.session.threads.length,2);assert.equal(f.session.resumePickerRequested,1);assert.equal(f.requests.some(r=>r.path.includes('/run?')),false);await f.session.submit('/resume two');assert.equal(f.session.threadId,'two');assert.equal(f.requests.some(r=>r.path.includes('/two/run?')),true);await assert.rejects(f.session.submit('/resume one two'));}finally{await f.close();}});

test('title generation runs independently after answer and remains bound to its original thread',async()=>{
 const f=await fixture();try{
  let complete!:(value:any)=>void;const pending=new Promise<any>(r=>complete=r);const original=f.session.client.json.bind(f.session.client);
  f.session.client.json=async(path,...args)=>path==='/app/conversations/title'?pending:original(path,...args);
  f.session.client.stream=async function*(){yield {type:'text-delta',payload:{text:'正常答案'}};yield {type:'finish',payload:{}};};
  const id=f.session.threadId;assert.equal(await f.session.submit('学习规划'),0);assert.equal(f.session.busy,false);assert.equal((f.session as any).titleTasks.has(id),true);
  f.session.threads=[{id,title:''}];await f.session.submit('/new');complete({title:'学习规划'});await (f.session as any).titleTasks.get(id);
  assert.equal(f.session.threads[0].title,'学习规划');assert.notEqual(f.session.threadId,id);
 }finally{await f.close();}
});
test('opening resume retries missing titles in order without blocking list or overwriting existing names',async()=>{
 const f=await fixture();try{
  f.session.client.threads=async()=>[{id:'missing',resourceId:'local',title:''},{id:'named',resourceId:'local',title:'已有标题'}];
  let calls=0;f.session.client.json=async(path,_method,body)=>{assert.equal(path,'/app/conversations/title');assert.equal(body.threadId,'missing');if(++calls===1)throw new Error('offline');return {title:'补回标题'};};
  await f.session.openResumePicker();assert.equal(f.session.resumePickerRequested,1);await (f.session as any).titleTasks.get('missing');assert.equal(f.session.threads[0].title,'');
  await f.session.openResumePicker();await (f.session as any).titleTasks.get('missing');assert.equal(f.session.threads[0].title,'补回标题');assert.equal(f.session.threads[1].title,'已有标题');assert.equal(calls,2);
 }finally{await f.close();}
});

test('notices opens a list without calling the model',async()=>{const f=await fixture();try{f.session.client.stream=async function*(){throw new Error('unexpected model call');};f.session.client.json=async path=>{assert.equal(path,'/app/notices?refresh=true');return {status:'completed',data:{results:[{title:'通知',url:'https://example.org',publishedAt:'2026-10-03'}]}};};await f.session.submit('/notices');assert.equal(f.session.page,'notices');assert.equal(f.session.noticeItems[0].title,'通知');}finally{await f.close();}});
