import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm,cp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
const root=await mkdtemp(join(tmpdir(),'seudaily-http-'));
await writeFile(join(root,'package.json'),'{}');await writeFile(join(root,'pyproject.toml'),'');
await mkdir(join(root,'.agent','skills'),{recursive:true});
await cp(new URL('../.agent/skills/training-plan-audit',import.meta.url),join(root,'.agent','skills','training-plan-audit'),{recursive:true});
process.env.SEUDAILY_PROJECT_ROOT=root;
const {app}=await import('../src/server/app.ts');
const {agentRuntime}=await import('../src/runtime/application.ts');
const {agentStore}=await import('../src/runtime/storage.ts');
const {agentInstructions}=await import('../src/runtime/instructions.ts');
const request=(path,body)=>app.request('http://127.0.0.1:4111'+path,{method:body?'POST':'GET',headers:{host:'127.0.0.1:4111','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
function input(thread,token,messages,resource='fixture'){return {messages,memory:{thread,resource},requestContext:{seudailyRunToken:token,seudailySkills:['training-plan-audit'],seudailyInterface:'cli'}};}
function events(text){return text.split('\n\n').filter(block=>block.startsWith('data: ')&&!block.includes('[DONE]')).map(block=>JSON.parse(block.slice(6)));}

test('HTTP skill discovery, AGENT.md settings and bound approval recovery',async t=>{
 t.after(async()=>{await agentRuntime.shutdown();await agentStore.close();await rm(root,{recursive:true,force:true});});
 // The normal chat upload endpoint must index automatically, without /knowledge add.
 const upload=async()=>{
  const form=new FormData();form.append('file',new File(['考试占比为百分之六十。'],'课程说明.txt'));
  return app.request('http://127.0.0.1:4111/app/documents',{method:'POST',headers:{host:'127.0.0.1:4111'},body:form});
 };
 const uploaded=await upload();assert.equal(uploaded.status,200);
 const document=await uploaded.json();assert.match(document.markdown,/百分之六十/);
 assert.equal(document.knowledge.duplicate,false);
 const again=await (await upload()).json();assert.equal(again.knowledge.duplicate,true);
 assert.equal(again.knowledge.id,document.knowledge.id);
 const {receiveWeChatFile,prepareWeChatFiles}=await import('../src/wechat/file-receiver.ts');
 const received=await receiveWeChatFile('课程说明.txt',Buffer.from(document.markdown),'fixture-file-source');
 assert.equal(await readFile(received.path,'utf8'),document.markdown);
 const refs=await prepareWeChatFiles([received],new AbortController().signal);
 const {resolveDocumentContexts}=await import('../src/runtime/document-context.ts');
 assert.equal(resolveDocumentContexts(refs)[0].markdown,document.markdown);
 assert.equal((await receiveWeChatFile('课程说明.txt',Buffer.from(document.markdown),'fixture-file-source')).path,received.path);
 const library=await (await request('/app/knowledge')).json();assert.equal(library.documents.length,1);
 const fileList=await (await request('/app/library?category=documents')).json();
 const storedFiles=fileList.files.filter(item=>item.category==='documents');
 assert.equal(storedFiles.length,1,'original and knowledge copies appear once');
 assert.equal(storedFiles[0].name,'课程说明.txt');
 const initial=await (await request('/app/library')).json();assert.equal(initial.level,'categories');assert.equal(initial.files.length,0);assert.equal(initial.directories.length,7);
 const articleDirectory=join(root,'.seudaily/jwc/articles'),metadataDirectory=join(root,'.seudaily/web-files/metadata'),originalDirectory=join(root,'.seudaily/web-files/files/jwc.seu.edu.cn');
 await Promise.all([articleDirectory,metadataDirectory,originalDirectory].map(path=>mkdir(path,{recursive:true})));
 const {createHash}=await import('node:crypto');const articleUrl='https://jwc.seu.edu.cn/2026/1007/c21681a1/page.htm';
 const attachments=[{name:'讲座预告.pdf',url:'https://jwc.seu.edu.cn/notice.pdf'},{name:'活动指南.pdf',url:'https://jwc.seu.edu.cn/guide.pdf'}];
 await writeFile(join(articleDirectory,'1.json'),JSON.stringify({id:'seu-jwc-1',title:'讲座预告',url:articleUrl,category:'practice',content:'通知正文',attachments}));
 for(const [index,item] of attachments.entries()){const bytes=Buffer.from('%PDF-fixture'+index),digest=createHash('sha256').update(bytes).digest('hex'),path=join(originalDirectory,digest+'.pdf');await writeFile(path,bytes);await writeFile(join(metadataDirectory,index+'.json'),JSON.stringify({...item,path,sourceUrl:articleUrl,sha256:digest}));}
 for(const [query,level] of [['category=web','sources'],['category=web&source=教务处','sections'],['category=web&source=教务处&section=实践教学','notices']]){const result=await (await request('/app/library?'+query)).json();assert.equal(result.level,level);assert.equal(result.files.length,0);assert.equal(result.directories.length,1);}
 const noticeFiles=await (await request('/app/library?category=web&source=教务处&section=实践教学&notice=seu-jwc-1')).json();assert.equal(noticeFiles.files.length,3);assert.equal(noticeFiles.files.filter(file=>file.type==='PDF').length,2);assert.ok(noticeFiles.files.every(file=>file.path.includes('/practice/seu-jwc-1/')));
 const firstPage=await (await request('/app/library?query=讲座预告&limit=1')).json();assert.equal(firstPage.count,2);assert.equal(firstPage.files.length,1);assert.equal(firstPage.nextCursor,'1');
 const nextPage=await (await request('/app/library?query=讲座预告&limit=1&cursor=1')).json();assert.equal(nextPage.files.length,1);assert.equal(nextPage.nextCursor,null);assert.notEqual(nextPage.files[0].path,firstPage.files[0].path);
 const download=await app.request('http://127.0.0.1:4111/app/library/preview?path='+encodeURIComponent(storedFiles[0].path)+'&download=1&name='+encodeURIComponent(storedFiles[0].name),{headers:{host:'127.0.0.1:4111'}});
 assert.equal(download.status,200);assert.match(download.headers.get('Content-Disposition'),/^attachment;/);
 assert.equal(await download.text(),document.markdown);
 const cached=JSON.parse(await readFile(join(root,'.seudaily','knowledge',document.knowledge.id+'.text.json'),'utf8'));
 assert.equal(cached.text,document.markdown);
 const invalidForm=new FormData();invalidForm.append('file',new File([new Uint8Array([0xff])],'invalid.txt'));
 const invalid=await app.request('http://127.0.0.1:4111/app/documents',{method:'POST',headers:{host:'127.0.0.1:4111'},body:invalidForm});
 assert.equal(invalid.status,422);
 assert.equal((await (await request('/app/knowledge')).json()).documents.length,1);
 const deleted=await app.request('http://127.0.0.1:4111/app/library',{method:'DELETE',headers:{host:'127.0.0.1:4111','Content-Type':'application/json'},body:JSON.stringify({path:storedFiles[0].path})});
 assert.equal(deleted.status,200);
 assert.equal((await (await request('/app/library')).json()).files.filter(item=>item.category==='documents').length,0);
 assert.equal((await (await request('/app/knowledge')).json()).documents.length,0);
 assert.equal((await (await request('/app/skills')).json()).skills[0].name,'training-plan-audit');
 const saved=await request('/app/settings',{agentInstructions:'FIXTURE_AGENT_RULE'});
 assert.equal(saved.status,200);
 assert.equal(await readFile(join(root,'AGENT.md'),'utf8'),'FIXTURE_AGENT_RULE');
 assert.equal((await (await request('/app/settings')).json()).agentInstructions,'FIXTURE_AGENT_RULE');
 assert.match(await agentInstructions({threadId:'x',resourceId:'x',runToken:'x'}),/FIXTURE_AGENT_RULE/);
 let executed=0,step=0;
 agentRuntime.config.tools=async()=>({probe:{id:'probe',description:'fixture',inputSchema:z.object({password:z.string()}),requireApproval:true,execute:async()=>{executed++;return {status:'completed'};}}});
 agentRuntime.config.provider={async *stream(){step++;yield {type:'complete',message:step%2?{role:'assistant',content:null,tool_calls:[{id:randomUUID(),type:'function',function:{name:'probe',arguments:'{"password":"fixture-private"}'}}]}:{role:'assistant',content:'done'}};}};
 const thread=randomUUID(),token=randomUUID();
 const first=await request('/api/agents/seudaily-agent/stream',input(thread,token,'test'));
 const approval=events(await first.text()).find(event=>event.type==='tool-approval-request').payload;
 const pending=(await (await request(`/api/memory/threads/${thread}/run?resourceId=fixture`)).json()).pending;
 assert.equal(pending.runToken,token);assert.equal(pending.args.password,'[已脱敏]');
 assert.equal((await request(`/api/memory/threads/${thread}/run?resourceId=wrong`)).status,404);
 const answer=[{role:'tool',content:[{type:'tool-approval-response',approvalId:approval.approvalId,approved:true}]}];
 assert.equal((await request('/api/agents/seudaily-agent/stream',input(thread,'wrong',answer))).status,400);
 const approved=await request('/api/agents/seudaily-agent/stream',input(thread,token,answer));
 assert.ok(events(await approved.text()).some(event=>event.type==='finish'));assert.equal(executed,1);
 assert.equal((await request('/api/agents/seudaily-agent/stream',input(thread,token,answer))).status,400);
 assert.equal((await request('/api/agents/seudaily-agent/stream',{...input('other','new','text'),requestContext:{seudailyRunToken:'new',seudailySkills:['unknown']}})).status,400);
});
