import test from 'node:test';import assert from 'node:assert/strict';
import {diskSize,courseForm,semesterForm,programStatusForm,settingsForm,focusForm} from '../src/terminal/management.js';
const fixture=()=>{const requests:any[]=[];const s:any={schedule:{customizations:{semester:{name:'秋季',startDate:'2026-09-20',totalWeeks:16},overrides:{},customCourses:[],dateOverrides:[]}},client:{json:async(...args:any[])=>{requests.push(args);if(args[0]==='/app/settings'&&args.length===1)return {fields:[{name:'API_KEY',secret:true,value:'',configured:true}],agentInstructions:'规则'};return {status:'completed'};}},result:(x:any)=>x,show:()=>{},loadSchedule:async()=>{},loadPrograms:async()=>{},loadFocus:async()=>{}};return {s,requests};};
const values=(f:any)=>Object.fromEntries(f.fields.map((x:any)=>[x.key,x.value]));
test('ramdisk capacity accepts case/space units and validates bounds',()=>{assert.equal(diskSize('512 mb'),'512M');assert.equal(diskSize('0.5 GB'),'512M');assert.equal(diskSize('1024'),'1024M');assert.throws(()=>diskSize('0 MB'));assert.throws(()=>diskSize('oops'));});
test('course form preserves remote identity, rejects invalid ranges, supports new/date courses',async()=>{const {s,requests}=fixture();const f=courseForm(s,{courseName:'原课',source:'remote',sourceKey:'key',weekday:2,startPeriod:3,endPeriod:4,weeks:[1,3]});await f.save({...values(f),courseName:'修改'});assert.equal(requests[0][2].overrides.key.courseName,'修改');assert.deepEqual(requests[0][2].overrides.key.weeks,[1,3]);await assert.rejects(f.save({...values(f),endPeriod:'2'}));const n=courseForm(s);await n.save({...values(n),courseName:'新增',date:'2026-10-03'});assert.equal(requests.at(-1)[2].dateOverrides[0].date,'2026-10-03');});
test('semester and program status write shared Web endpoints',async()=>{const {s,requests}=fixture();const f=semesterForm(s);await f.save({...values(f),totalWeeks:'20'});assert.equal(requests[0][2].semester.totalWeeks,20);const p=programStatusForm(s,'plan',{id:'course',name:'课程',semesterOptions:[{value:'2026-1',label:'秋季'}]});await p.save({...values(p),status:'completed'});assert.deepEqual(requests.at(-1),['/app/programs/course-status','PATCH',{planId:'plan',courseId:'course',semester:'2026-1',status:'completed'}]);});
test('settings masks existing secrets and saves AGENT.md separately',async()=>{const {s,requests}=fixture();const f=await settingsForm(s);assert.equal(f.fields[0].secret,true);assert.equal(f.fields[0].value,'');await f.save({...values(f),agentInstructions:'新规则'});assert.equal(requests.at(-1)[2].agentInstructions,'新规则');assert.equal(requests.at(-1)[2].values.API_KEY,'');});
test('focus saves enabled as boolean',async()=>{const {s,requests}=fixture();const f=focusForm(s);await f.save({...values(f),title:'通知',description:'关注新闻',enabled:'false'});assert.equal(requests.at(-1)[2].enabled,false);});
